# -*- coding: utf-8 -*-
"""AI-Driven Sales Forecasting & Customer Feedback Intelligence System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LbpLXtLqKzrP7rLrpHAVou-elmictF10
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from textblob import TextBlob
import nltk
nltk.download('stopwords')

df = pd.read_csv("/content/retail_ai_dataset.csv")
df.head()

df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

exog = df[['temperature', 'holiday', 'promotion']]
model = SARIMAX(df['sales'], exog=exog, order=(1,1,1), seasonal_order=(1,1,1,7))
results = model.fit()

forecast = results.predict(start=len(df), end=len(df)+6,
                           exog=exog.tail(7))

print("\n📈 SALES FORECAST:")
print(forecast)

plt.figure(figsize=(10,5))
plt.plot(df['sales'], label="Actual")
plt.plot(forecast, label="Forecast", color='red')
plt.legend()
plt.title("Sales Forecast")
plt.show()

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

df['sentiment_score'] = df['customer_feedback'].apply(get_sentiment)
df['sentiment'] = df['sentiment_score'].apply(lambda x: "Positive" if x>0 else "Negative")

print("\n🧠 SENTIMENT RESULTS:")
print(df[['customer_feedback','sentiment']].head())

df['label'] = df['sentiment'].map({"Positive":1, "Negative":0})

X_train, X_test, y_train, y_test = train_test_split(
    df['customer_feedback'], df['label'], test_size=0.2)

text_model = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('clf', LogisticRegression())
])

text_model.fit(X_train, y_train)
accuracy = text_model.score(X_test, y_test)

print(f"\n📊 Feedback Classifier Accuracy: {accuracy*100:.2f}%")

avg_sentiment = df['sentiment_score'].mean()
avg_sales = df['sales'].mean()

def generate_insight():
    if avg_sentiment > 0:
        mood = "positive"
    else:
        mood = "negative"

    return f"""
    🔍 AI INSIGHT REPORT
    -------------------------
    Average Sales: {avg_sales:.2f}
    Overall Customer Mood: {mood}
    Forecast Trend: Increasing sales expected due to promotions & holidays.
    Key Driver: Customer sentiment strongly influences sales performance.
    Recommendation: Increase marketing during high-sentiment periods.
    """

print(generate_insight())

print("\n✅ END-TO-END AI SYSTEM EXECUTED SUCCESSFULLY")

